services:
  postgres:
    image: postgres:15
    container_name: educabot_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - educabot-net
    command: ["postgres", "-c", "max_connections=1000"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432 # host:container
    expose:
      - 5432
  redis:
    image: redis:latest
    container_name: educabot_redis
    restart: always
    networks:
      - educabot-net
    command: >
      redis-server --port 6379 --appendonly yes
    env_file:
      - .env
    volumes:
      - redis_data:/data
    ports:
      - 6380:6379 # host:container
  evolution-api:
    image: evoapicloud/evolution-api:v2.3.0
    container_name: educabot_evolution
    restart: always
    networks:
      - educabot-net
    env_file:
      - .env
    volumes:
      - evolution_data:/evolution/instances
    ports:
      - 8080:8080 # host:container
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
  evolution_data:

networks:
  educabot-net:
    name: educabot-net
    driver: bridge
