"""Create Gestor table

Revision ID: 35a709e53893
Revises: 
Create Date: 2026-06-17 18:32:53.682196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a709e53893'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('escola', sa.String(length=255), nullable=False),
    sa.Column('pode_pedir_gas', sa.Boolean(), nullable=False),
    sa.Column('pode_pedir_agua', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gestores_id'), 'gestores', ['id'], unique=False)
    op.create_index(op.f('ix_gestores_telefone'), 'gestores', ['telefone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gestores_telefone'), table_name='gestores')
    op.drop_index(op.f('ix_gestores_id'), table_name='gestores')
    op.drop_table('gestores')
    # ### end Alembic commands ###
