"""initial schema

Revision ID: 3c1352d37922
Revises: 
Create Date: 2026-06-19 19:38:38.220297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1352d37922'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('instituicao', sa.String(length=255), nullable=False),
    sa.Column('pode_pedir_gas', sa.Boolean(), nullable=False),
    sa.Column('pode_pedir_agua', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gestores_id'), 'gestores', ['id'], unique=False)
    op.create_index(op.f('ix_gestores_telefone'), 'gestores', ['telefone'], unique=True)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('GAS', 'AGUA', name='tipo_pedido'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gestor_id'], ['gestores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_gestores_telefone'), table_name='gestores')
    op.drop_index(op.f('ix_gestores_id'), table_name='gestores')
    op.drop_table('gestores')
    # ### end Alembic commands ###
